### ISSUE TITLE
Sending a scout destroyed all buildings of visited player

### ISSUE THREAD

**Issue by edvordo** [koodilab/galaxyofdrones-online#1]
### Me (Etalz)
Level: 5
Unit: Icarus (Scout ship)

### Friend (Saamoot)
Level: 2
Buildings: Command Center, Power Plant, 3 Mines, Drone Hangar, Storage Hangar and a Turret

## Problem
I sent the Icarus (scout ship!) to Saamoots' planet.

Apparently, there was a battle ([Battle log](https://i.imgur.com/fshLmIR.png)) and it destroyed everything he had ([Screenshot](https://i.imgur.com/U6YgXsq.jpg)), including the Command Center.

He cannot do anything, he is basically stuck. I don't think this is okay! They cannot try and rebuild.

-------------

Browsing through code, I've discovered this condition [Source](https://github.com/koodilab/galaxyofdrones-online/blob/master/app/Battle/Simulator.php#L359)
```php
            if ($losses || $grid->building->type == Building::TYPE_DEFENSIVE || $this->battleLog->type == BattleLog::TYPE_SCOUT) {
                $grid->demolishBuilding($losses);
```
If I'm reading it right, this means that whenever a player receives a visit by Scout (and looses?) the battle, all of their buildings get destroyed.

Maybe [there](https://github.com/koodilab/galaxyofdrones-online/blob/master/app/Models/Concerns/HasBuilding.php#L110) should be a condition to not destroy ([disassociate](https://github.com/koodilab/galaxyofdrones-online/blob/master/app/Models/Concerns/HasBuilding.php#L133)) the Command Center at least.

**Comment by petaki** [comment]
Thank you for your report! Yes, we create the building log entry:

- if the building is damaged
- if the building is defensive building
- if this is a scout battle

But we need an other check before demolish. [Fixed #1](https://github.com/koodilab/galaxyofdrones-online/commit/ec706c597b5222035bedc44dddc45085d1d93caf)

**Comment by petaki** [comment]
I restored the command center and the 3 mines

**Comment by edvordo** [comment]
Thank you!

We're going to re-test if that fixed it :) Will report back in ~40 minutes ..

**Comment by edvordo** [comment]
It's stuck ![](https://i.imgur.com/otYO4Xp.png)

**Comment by petaki** [comment]
Fixed, thanks
