### ISSUE TITLE
[minor_ui_glitch] buttons dissapear on zoom out

### ISSUE THREAD

**Issue by iSimonL** [koodilab/galaxyofdrones-online#10]
Seen in: SWare Iron
On changing browser Window zoom state to values below 100% buttons at left bar and top right
dissapear. Easy to hit with ctrl+Mwheel, and took me a minute to figure out whats wrong...

**Comment by petaki** [comment]
Thanks for the report. What is your resolution? Could you take a screenshot?

**Comment by iSimonL** [comment]
appears at 1280x102 and 1920*1080
https://image.ibb.co/g3rREG/god_bug_02.png

**Comment by petaki** [comment]
Thank you for the resolution and screenshot, It helped to reproduce and [fix](https://github.com/koodilab/galaxyofdrones-online/commit/53021ed5d7335d979671e4fd6314cfc51fc3559b)
