### ISSUE TITLE
Instant transport drones are stuck @ 00:00:00 delivery time

### ISSUE THREAD

**Issue by edvordo** [koodilab/galaxyofdrones-online#14]
Sending resources from a planet where the Mothership is at, freezes the drones in place, stuck at 00:00:00 delivery time.

![image](https://user-images.githubusercontent.com/6738779/35296217-aa8df314-007b-11e8-90e5-4e72e880ece5.png)

**Comment by petaki** [comment]
Thank you for your report, I added a possible solution, and manually finished the stuck movements.

**Comment by edvordo** [comment]
Seems like it's solved, the next transport finished correctly

**Comment by DEMENT0R** [comment]
Similar problem:
![](https://i.imgur.com/r65QOrw.jpg)
