### ISSUE TITLE
Transport of Cobolt and Chronoton get lost forever.

### ISSUE THREAD

**Issue by ryanrca** [koodilab/galaxyofdrones-online#15]
I've researched Cobolt and Chronoton and have other planets mining them.
When I try to transport them to my planet with the mothership, the transport goes fine.
When it completes, counts of Cobolt and Chronoton on the mothership planet are still zero.

Why?  There is plenty of storage space available. 

When the transport ship returns the mining planet, it's numbers of mined material are not replaced.  It looks like they are lost forever!

**Comment by petaki** [comment]
Thanks, It is same as #14, and now [Fixed](https://github.com/koodilab/galaxyofdrones-online/commit/fdfc9d4e46e3475c1b7a2239815bcf4382ee066e)
