### ISSUE TITLE
[minor] Train time reduction not displayed (but is applied)

### ISSUE THREAD

**Issue by edvordo** [koodilab/galaxyofdrones-online#2]
Drone factory level 2 provides a 3% reduction to unit training time.

This reduction is however not shown before starting the training of a given unit
![](https://i.imgur.com/MB9mTvY.png)

However, it is [applied when actually training a unit](https://github.com/koodilab/galaxyofdrones-online/blob/master/app/Http/Controllers/Api/TrainerController.php#L77), the countdown started with reduced time.

**Comment by petaki** [comment]
Thank you! [Fixed #2](https://github.com/koodilab/galaxyofdrones-online/commit/4939d2662c3039215f35e21cf1ff20c509a74ce5)

**Comment by edvordo** [comment]
[Same thing while in training](https://github.com/koodilab/galaxyofdrones-online/blob/master/app/Models/Concerns/HasUnit.php#L26)
![image](https://user-images.githubusercontent.com/6738779/34630938-719e64e6-f26e-11e7-9d57-0e0e3594091b.png)

**Comment by petaki** [comment]
Thanks, [Fixed](https://github.com/koodilab/galaxyofdrones-online/commit/db687c710a00e35c503a747128ec3d6c78d2c8d7)
