### ISSUE TITLE
Uncompletable missions

### ISSUE THREAD

**Issue by edvordo** [koodilab/galaxyofdrones-online#3]
I've researched Cobalt (blue res.), because I wanted to check whether researching that resource will unlock the button to Occupy a planet with that resource (which it did).

The problem here is, that I did not have the research for Helios (Occupy ship) completed at that point (so I cannot occupy other planets), but I started getting missions that are entirely about or include Cobalt.

This means I cannot complete missions when I get a "behaving" RNG that generates mission with Cobalt ([which happened to me](https://i.imgur.com/6xIOViW.png)). I've been stuck with missions I cannot complete for over 24 hours now and it effectively halted my progress.

I know I can convert Alginite to Energy, but that takes a while to pile up.

Solution could be 

* to add a constraint [to the query that pulls unlocked resources](https://github.com/koodilab/galaxyofdrones-online/blob/master/app/Models/Queries/FindResourcesOrderBySortOrder.php#L16) to check, whether a player occupies a planet with that resources
* or modify the [command that generates the missions](https://github.com/koodilab/galaxyofdrones-online/blob/master/app/Console/Commands/MissionGenerateCommand.php#L69) to filter only resources from planets a player occupies

Just suggestions from digging around the code 🙂 

I think this could be a nice Quality-of-Life thing for players.

**Comment by petaki** [comment]
Yes, I agree, the purpose of the original solution was to increase the difficulty of the game.

**Comment by edvordo** [comment]
Well, I don't have too big of a problem with it staying like it is now, but at least add a warning, what is going to happen. After that, if a player chooses to proceed, it's their own fault for being stuck.

**Comment by petaki** [comment]
The next mission generation will be good :) [Fixed #3](https://github.com/koodilab/galaxyofdrones-online/commit/8434fa3b3e92712a0db851d2ce790a0c6fef6d27)

**Comment by edvordo** [comment]
Thanks! :)
