### ISSUE TITLE
Modals ignore custom planet names

### ISSUE THREAD

**Issue by edvordo** [koodilab/galaxyofdrones-online#4]
Modals (Scout/Attack/Occupy/etc.) use [planet->name](https://github.com/koodilab/galaxyofdrones-online/blob/master/resources/views/site/starmap/time.twig#L5) instead of [planet->display_name](https://github.com/koodilab/galaxyofdrones-online/blob/master/app/Models/Transformers/PlanetTransformer.php#L25)
  
![image](https://user-images.githubusercontent.com/6738779/34631645-afcf7720-f271-11e7-8503-5363645a7523.png)

**Comment by petaki** [comment]
Thanks, [Fixed #4](https://github.com/koodilab/galaxyofdrones-online/commit/f07065696e33fcbd8035f3e75283d75db9241926)
