### ISSUE TITLE
[suggestion] Missions/Resources overview

### ISSUE THREAD

**Issue by edvordo** [koodilab/galaxyofdrones-online#6]
The game could use some sort of overview of active missions (and maybe resources) on all occupied planets. [I've coded myself a script for this purpose](https://user-images.githubusercontent.com/6738779/34867307-f1cd803c-f77f-11e7-9e2c-174a6b5565b4.png), it's not perfect, of course, but it helped a lot.

**Comment by edvordo** [comment]
Actually, never mind, [this got a little ridiculous](https://user-images.githubusercontent.com/6738779/35006443-f61ce5b8-faf6-11e7-837e-9f676b4b4e02.png) when I occupied more planets.

**Comment by petaki** [comment]
Thank you for your suggestion. The current mission system was enough to launched the alpha version, but it is not suitable for the big planet number. Therefore I redesigned it, below you can read the new ruleset:

- The resources for the missions must be stored on the Mothership
- The capacity of Mothership is based on the level of user
- You can see and complete missions on the Mothership window
- You must send the mission resources from the Trade Office
- You need Goliath ships to send resources
- The sending time is instant from the capital planet
- For normal planets, it is based on the travel time

**Comment by petaki** [comment]
The new mission system is now available :)
