### ISSUE TITLE
[suggestion] Add a way to deconstruct already built building

### ISSUE THREAD

**Issue by edvordo** [koodilab/galaxyofdrones-online#8]
I've made a couple mistakes where I've accidentally built the wrong type building. 

Now, I know this is completely my fault, should have been more careful (or rather pay more attention to what I was doing).

But I'd welcome a way to deconstruct/destroy a building. There could maybe be a constraint to make this available for only level 1 building and it would cost Energy? I don't know, I guess this is up to you guys.

**Comment by petaki** [comment]
Thanks, I added it to UI. Previously this was just a console command.
