### ISSUE TITLE
Ressorces multiple times transmuteable

### ISSUE THREAD

**Issue by iSimonL** [koodilab/galaxyofdrones-online#9]
sometimes, in about 1 out of <100 cases, the ressources aint substaracted at tansmutation.
For ingame Log check Player: SimonLi ~20:55, transmuted ~7k Alginite twice, Planet name: Gallifrey.
Browser SWAre Iron - Version 58.0.3050.0. 

Another log, to figure it out could be, 17.01.2018 around 14:00,  around 45 Minutes before i made the Helios Update, there was a transmutation where i was able to transmute 1k Minerals, aprrox 6 Times. That was the point where i recognized that bug.

If you need any further details, you may contact me. Great Project.
simon_link@gmx.de

**Comment by iSimonL** [comment]
would it help if i get a timestamp within the minute, and note the exact values of ressources, the sheme is always, happened again... trying to transmute 723 alginite. -cliking field, scrolling mousewhell, or typing- 
click transmute, i get 723+5% energy, (724) appears in the field, i click, enter 700 sroll to 724 -> transmutate, get 725+5% energy, (725) appears in the transmute field... works somtimes 2 times, sometimes up to 3 or 4 times.

**Comment by iSimonL** [comment]
and again, seconds ago 184, 185, 186 - transmuted.

**Comment by iSimonL** [comment]
fund a clue, the websocekt sends authentification requests twice, http://www.warfreaks.com/pics/ws_log.JPG loooks horribly familiar to me, smellst like the nasty javascript bug sending requests multiple times, when document format got errors. but just a shot into the blue.

**Comment by iSimonL** [comment]
happened again, more details: 
http://www.warfreaks.com/pics/bug_occured_details.png
if it helps. i've saved the packet's exchanged during that.

**Comment by iSimonL** [comment]
it gets worse....
https://www.youtube.com/watch?v=_mvqnTkUytM&feature=youtu.be

**Comment by petaki** [comment]
Thanks for the report, I can not reproduce this, but we are investigating. After the multiple transmutations, did your energy increase?

**Comment by iSimonL** [comment]
yes, energy increased, made about 500k energy out of that 9k res.
If i'm able to help you with that, just ask, no problem. Also no problem if you need 
to login into my account to figure it out, just change pw if you need to, and send me the new one via email.,

**Comment by iSimonL** [comment]
maybe an important question to answer if you see those packetlogs, no i have'nt tried anything yet to confuse the server, just intentional use of the game client so far.

**Comment by iSimonL** [comment]
next thing i will watch: got my 2nd planet now, i will tell you if it happens there also....

**Comment by iSimonL** [comment]
frequency of occurance seems to be raising. now at 1 out of <30 and i'm able to tranmute res ~6(+/-)times.

**Comment by petaki** [comment]
Please try it again, I added a possible solution.

**Comment by iSimonL** [comment]
ok, testing.

**Comment by iSimonL** [comment]
no, happened again. if you want to reproduce it yourself, just log into my account and transmute 30 times.

**Comment by iSimonL** [comment]
i am logged of, so you may use that account for testing purposes.

**Comment by petaki** [comment]
If you can, test it again please.

**Comment by iSimonL** [comment]
ok, testing.

**Comment by petaki** [comment]
I added the fix to the backend and it solved the UI.

Thank you for your contribution. I will close this tomorrow.

**Comment by iSimonL** [comment]
ok, got some more transmutations done ~50+ looks very promising, yes fix looks very promising.
And did'nt even had to ask what you did to fix it. Thanks for the fast response, and thanks for making such a great project open source! Great Work! i will test for some more hour's and let you know if it occurs again.

**Comment by iSimonL** [comment]
~200 transmutations later. seems to be fixed properly.

**Comment by iSimonL** [comment]
you may reset my energy count when you close the bug, i think i got a little starting bonus out of it ;) , but with additional 250k energy it's getting boring :D

**Comment by petaki** [comment]
Thank you for your feedback :) I decreased by 100k units of energy.
